WebApplication_WithImage/Models/DetailsModal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication_WithImage.Models
{
    public class DetailsModal
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name  { get; set; }
        public string DocumentName { get; set; }
        public string Path { get; set; }

        [NotMapped]
        [Display(Name ="Choose Image")]
        public IFormFile ImagePath { get; set; }

    }
}

WebApplication_WithImage/Models/ErrorViewModel.cs
namespace WebApplication_WithImage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication_WithImage/Controllers/DetailsModalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using WebApplication_WithImage.Data;
using WebApplication_WithImage.Models;

namespace WebApplication_WithImage.Controllers
{
    public class DetailsModalController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IWebHostEnvironment _environment;

        public DetailsModalController(AppDBContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: DetailsModal/Index
        public IActionResult Index()
        {
            var data =  _context.detailsModals.ToList();
            return View(data);
        }

        public IActionResult Details(int Id)
        {
            var data =_context.detailsModals.FirstOrDefault(x=> x.Id==Id);
            return View(data);
        }


        // GET: DetailsModal/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: DetailsModal/Create
        [HttpPost]
        public IActionResult Create(DetailsModal modal)
        {
            
            try
            {
                if (modal!=null)
                {
                    string uniquieFileName = UploadImage(modal);
                    var data = new DetailsModal()
                    {
                       
                        Title = modal.Title, 
                        Name= modal.Name,
                        DocumentName = modal.DocumentName,
                        Path=uniquieFileName

                    };

                    _context.detailsModals.Add(data);
                    _context.SaveChanges();
                    TempData["Success"] = "Succcessfully saved";
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError(string.Empty, "Nowt saved..... modal property is not valid");

            }
            catch(Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }

            return View (modal);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = _context.detailsModals.FirstOrDefault(x=> x.Id==id);
            if (data != null)
            {
                return View(data);
            }
            else
            {
                return View();
            }
        }


        [HttpPost]
        public ActionResult Edit(int id, DetailsModal detailsModal)
        {
            try
            {
                var data = _context.detailsModals.FirstOrDefault(x => x.Id == id);
                if (detailsModal != null)
                {
                    data.Title = detailsModal.Title;
                    data.Name = detailsModal.Name;
                    data.DocumentName = detailsModal.DocumentName;
                    data.Title = detailsModal.Title;

                    if (detailsModal.ImagePath != null)
                    {
                        var uniquiePic = UploadImage(detailsModal);
                        data.Path = uniquiePic;

                    }

                    _context.detailsModals.Add(data);
                    _context.SaveChanges();
                    TempData["Success"] = "Succcessfully updated";
                    return RedirectToAction("Index");

                }

                ModelState.AddModelError(string.Empty, "Update Fail....");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty,ex.Message);
            }
            return View();
        }

        // GET: DetailsModal/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var modal = _context.detailsModals.Find(id);
            if (modal == null)
            {
                return NotFound();
            }
            return View(modal);
        }

        // POST: DetailsModal/Delete/5
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var modal = _context.detailsModals.Find(id);
            if (modal != null)
            {
                _context.detailsModals.Remove(modal);
                _context.SaveChanges();
                TempData["Success"] = "Successfully deleted";
            }
            return RedirectToAction("Index");
        }



        private string UploadImage(DetailsModal modal)
        {
            string uniqueFileName = string.Empty;

            if (modal.ImagePath != null)
            {
                string uploadFolder = Path.Combine(_environment.WebRootPath, "Images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + modal.ImagePath.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    modal.ImagePath.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }


    }
}

WebApplication_WithImage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication_WithImage.Models;

namespace WebApplication_WithImage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication_WithImage/Views/DetailsModal/Create.cshtml
@model WebApplication_WithImage.Models.DetailsModal

<h1 class="text-center">Creatw Form</h1>
<hr />
<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <!-- Title field -->
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input type="text" asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <!-- Name field -->
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <!-- DocumentName field -->
    <div class="form-group">
        <label asp-for="DocumentName" class="control-label"></label>
        <input type="text" asp-for="DocumentName" class="form-control" />
        <span asp-validation-for="DocumentName" class="text-danger"></span>
    </div>

    <!-- Image upload -->
    <div class="form-group">
        <label asp-for="ImagePath" class="control-label"></label>
        <input type="file" asp-for="ImagePath" class="form-control" />
        <span asp-validation-for="ImagePath" class="text-danger"></span>
    </div>


    <input type="submit" value="Create" class="btn btn-primary" />
</form>

<a class="btn btn-primary" asp-action="Index"> Back to Index</a>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebApplication_WithImage/Views/DetailsModal/Delete.cshtml
@model WebApplication_WithImage.Models.DetailsModal

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetailsModal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
        @if (!string.IsNullOrEmpty(Model.Path))
        {
            <div class="form-group">
                <label>Current Image</label>
                <br />
                <img id="img-@Model.Id" src="/Images/@Model.Path" alt="@Model.Name" style="width:200px;height:200px;" />
            </div>
        }
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication_WithImage/Views/DetailsModal/Details.cshtml
@model WebApplication_WithImage.Models.DetailsModal

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DetailsModal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
            
        </dd>
        @if (!string.IsNullOrEmpty(Model.Path))
        {
            <div class="form-group">
                <label>Current Image</label>
                <br />
                <img id="img-@Model.Id" src="/Images/@Model.Path" alt="@Model.Name" style="width:200px;height:200px;" />
            </div>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication_WithImage/Views/DetailsModal/Edit.cshtml
@model WebApplication_WithImage.Models.DetailsModal

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DetailsModal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentName" class="control-label"></label>
                <input asp-for="DocumentName" class="form-control" />
                <span asp-validation-for="DocumentName" class="text-danger"></span>
            </div>
            <!-- Display the current image if it exists -->
            @if (!string.IsNullOrEmpty(Model.Path))
            {
                <div class="form-group">
                    <label>Current Image</label>
                    <br />
                    <img id="img-@Model.Id" src="/Images/@Model.Path" alt="@Model.Name" style="width:200px;height:200px;" />
                </div>
            }
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input type="hidden" asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <!-- Image upload -->
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input type="file" asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication_WithImage/Views/DetailsModal/Index.cshtml
@model IEnumerable<WebApplication_WithImage.Models.DetailsModal>

@{
    ViewData["Title"] = "Index";
}

<h1>List Of Persons</h1>

<p>
    <a class="btn btn-primary p-1 m-1" asp-controller="DetailsModal" asp-action="Create">Create New</a>
</p>



<div class="container">
    <div class="row">
        <div class="text-center text-primary">Details</div>
        <table class="table table-bordered">
            <thead>
                <tr class="text-center bg-dark text-light">
                    <th>Id</th>
                    <th>Title</th>
                    <th>Name</th>

                    <th>Document</th>

                    <th>Image</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="text-center">
                @if (Model != null)
                {
                    @foreach(var d in Model)
                    {
                        <tr>
                            <td>@d.Id</td>
                            <td>@d.Title</td>
                            <td>@d.Name</td>
                            <td>@d.DocumentName</td>
                            <td>
                                <img id="img-@d.Id" src="/Images/@d.Path" alt="@d.Name" style="width:100px;height:100px;" />
                            </td>

                            <td>
                                <a asp-action="Edit" asp-route-id="@d.Id">Edit</a> |
                                <a asp-action="Details" asp-route-id="@d.Id">Details</a> |
                                <a asp-action="Delete" asp-route-id="@d.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>

    </div>
</div>

WebApplication_WithImage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication_WithImage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication_WithImage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication_WithImage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication_WithImage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DetailsModal" asp-action="Index">Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication_WithImage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>